//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdonnhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ctdonnhap()
        {
            this.thungsaches = new HashSet<thungsach>();
        }
    
        public int MaCTDonNhap { get; set; }
        public int MaSach { get; set; }
        public int MaDN { get; set; }
        public int SoLuong { get; set; }
        public int GiaNhap { get; set; }
    
        public virtual donnhap donnhap { get; set; }
        public virtual sach sach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thungsach> thungsaches { get; set; }
    }
}
