//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donnhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donnhap()
        {
            this.ctdonnhaps = new HashSet<ctdonnhap>();
        }
    
        public int MaDN { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public int MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonnhap> ctdonnhaps { get; set; }
        public virtual nguoidung nguoidung { get; set; }
        public virtual nguoidung nguoidung1 { get; set; }
    }
}
