//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sach()
        {
            this.ctdonnhaps = new HashSet<ctdonnhap>();
            this.ctdonxuats = new HashSet<ctdonxuat>();
            this.thungsaches = new HashSet<thungsach>();
        }
    
        public int MaSach { get; set; }
        public int MaTheLoai { get; set; }
        public int MaTacGia { get; set; }
        public int MaNXB { get; set; }
        public string TenSach { get; set; }
        public string TomTat { get; set; }
        public Nullable<int> TongSoTrang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Tap { get; set; }
        public Nullable<int> TongSoTap { get; set; }
        public Nullable<double> GiaTriSach { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public string GioiThieu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonnhap> ctdonnhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonxuat> ctdonxuats { get; set; }
        public virtual nhaxb nhaxb { get; set; }
        public virtual theloai theloai { get; set; }
        public virtual tacgia tacgia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thungsach> thungsaches { get; set; }
    }
}
