//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thungsach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thungsach()
        {
            this.vitris = new HashSet<vitri>();
        }
    
        public int MaThung { get; set; }
        public int MaSach { get; set; }
        public Nullable<int> MaCTDonXuat { get; set; }
        public Nullable<int> MaCTDonNhap { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> SoLuongSach { get; set; }
    
        public virtual ctdonnhap ctdonnhap { get; set; }
        public virtual ctdonxuat ctdonxuat { get; set; }
        public virtual sach sach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vitri> vitris { get; set; }
    }
}
