//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vitri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vitri()
        {
            this.vitri1 = new HashSet<vitri>();
        }
    
        public int MaViTri { get; set; }
        public Nullable<int> MaThung { get; set; }
        public Nullable<int> MaViTriCha { get; set; }
        public string TenViTri { get; set; }
        public Nullable<int> LoaiViTri { get; set; }
        public string Nha { get; set; }
        public Nullable<int> Ke { get; set; }
        public Nullable<int> Tang { get; set; }
        public Nullable<int> O { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual thungsach thungsach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vitri> vitri1 { get; set; }
        public virtual vitri vitri2 { get; set; }
    }
}
